version: '3'
services:
  postgres:
    image: 'postgres:12'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_PASSWORD=sXe--123'
      - 'POSTGRES_DB=messenger_db'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8090:8090"